import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import {
    Divider,
    List,
    ListItem,
    ListItemButton,
    ListItemIcon,
    ListItemText,
} from '@mui/material';
import MobileHeader from '@/components/layout/MobileHeader/MobileHeader';
import MobileNavbar from '@/components/layout/MobileNavbar/MobileNavbar';
import { category } from '@/types/category';
import PCHeader from '@/components/layout/PCHeader/PCHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="md:hidden fixed top-0 left-0 right-0">
                    <MobileHeader />
                </header>
                <nav className="hidden md:block fixed top-0 left-0 right-0 bg-white border-b-2 border-borderLightTheme shadow-[0_4px_12px_rgba(0,0,0,0.1)]">
                    <PCHeader />
                </nav>
                <nav className="flex md:hidden fixed bottom-0 left-0 right-0">
                    <MobileNavbar />
                </nav>
                <main className="container mt-14 sm:mt-16 md:mt-[125px]">
                    {children}
                </main>
            </body>
        </html>
    );
}
