import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './GlobalStyle.scss';
import './_variables.scss';
import MobileHeader from '@/components/layout/MobileHeader/MobileHeader';
import MobileNavbar from '@/components/layout/MobileNavbar/MobileNavbar';
import PCHeader from '@/components/layout/PCHeader/PCHeader';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="md:hidden fixed top-0 left-0 right-0 z-50">
                    <MobileHeader />
                </header>
                <nav className="hidden md:block fixed top-0 left-0 right-0 bg-white border-b-2 border-borderLightTheme shadow-[0_4px_12px_rgba(0,0,0,0.1)] z-50">
                    <PCHeader />
                </nav>
                <nav className="flex md:hidden fixed bottom-0 left-0 right-0 z-50">
                    <MobileNavbar />
                </nav>
                <main className="mt-14 sm:mt-16 md:mt-[125px]">
                    <StoreProvider>{children}</StoreProvider>
                </main>
            </body>
        </html>
    );
}
